### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by herz-ag** [Timthreetwelve/WUView#15]
### Brief summary of your request

keyboard

### Request details

Can you please add keyboard support for your nice little program?
Thanks,
herz.AG

**Comment by Timthreetwelve** [comment]
@herz-ag, could you elaborate more on what you want to be able to do via the keyboard?

**Comment by herz-ag** [comment]
I'd like to scroll through the updates via scrollkeys up+down or page up/down.

**Comment by Timthreetwelve** [comment]
@herz-ag I just wanted to add a comment to let you know that I'm working on this, but I'm not satisfied with it yet.  I appreciate your patience.

Tim

**Comment by Timthreetwelve** [comment]
@herz-ag, I've got this working. I'm not 100% happy with the results so I may revisit it if I gain any more insight. This enhancement will also be included in 0.5.12. 

I'm also adding an option to select the first row in the grid at startup. With this option enabled there's no obvious way to know that you've tabbed into the grid using keyboard navigation since the first row is already highlighted. You may decide to leave this new option unchecked.

Tim
