### ISSUE TITLE
Bug Report: app v. 0.5.23.0 - Multilanguage installer issues

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/WUView#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have read the Known Issues and Troubleshooting topics in the Wiki

### What happened or didn't happen

@Timthreetwelve 

Thanks for multilanguage installer.

Please check screenshot for details

![image](https://github.com/Timthreetwelve/WUView/assets/1262554/9a7ebeaa-b10b-4c27-979c-396944950534)

-Exe file properties
Copyright (red box) is not ncessary
Copyright is already the field name
(c) and Copyright are equeal. leave just (c)

![image](https://github.com/Timthreetwelve/WUView/assets/1262554/f52adca3-bdcc-4d31-b708-4d353f1f0b73)

In caption text is missing app version number.
It's better to have it in Caption because is vsible in all installer windows.

I have some doubts about installer strings like "Si noti .."

### Steps To Reproduce

Install the application

### Version

0.5,23.0

### Windows Version

Windows 11 22H2

### Anything else?

What version of Inno Setup are you using?
May I have instalelr script for a deep check?

**Comment by Timthreetwelve** [comment]
@bovirus I'm using Inno Setup version 6.2.2. The .iss file is [here](https://github.com/Timthreetwelve/WUView/blob/main/WUView/Inno_Setup/WUView.iss). The language files are not located in the project as they are common to my other projects, but I've attached the Itailian.isl (renamed to .txt since GitHub wouldn't allow .isl).  
[Italian.isl.txt](https://github.com/Timthreetwelve/WUView/files/12753068/Italian.isl.txt)

I'll investigate the Inno docs and see if I can find how to add version number to the window title. Unless you have that information handy.

**Comment by Timthreetwelve** [comment]
I have the version number added to the installer title bar and the copyright statement updated. c1dae5c758134cf151daf16d867f845ea29876d3

**Comment by Timthreetwelve** [comment]
I believe that the above items have been addressed in the latest release.
